apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: orchestrator-rolebinding
subjects:
  - kind: ServiceAccount
    name: orchestrator-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: orchestrator-role
  apiGroup: rbac.authorization.k8s.io
